-- ============================================================
-- 회원가입 UI에 맞춘 public.employees 테이블
-- Supabase 대시보드 > SQL Editor에서 이 파일 전체 실행
--
-- ※ Auth > Users 에 보이는 건 "로그인 계정"만 있습니다.
--    회원가입 폼에서 입력한 이름·전화·전시장·팀·생년월일·직책 등은
--    아래 테이블(public.employees)에 저장됩니다.
--    확인: Table Editor > employees
-- ============================================================

-- employees 테이블이 없으면 생성 (이미 있으면 무시)
CREATE TABLE IF NOT EXISTS public.employees (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now()
);

-- 회원가입 UI 필드에 맞춘 컬럼 (없으면 추가)
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS team text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS showroom text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS birth_date date;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS position_name text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS role text DEFAULT 'staff';
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS permission text DEFAULT 'staff';

-- 로그인·승인 관련
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS auth_user_id uuid UNIQUE;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS employee_id text UNIQUE;

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_employees_auth_user_id ON public.employees(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_employees_employee_id ON public.employees(employee_id);
CREATE INDEX IF NOT EXISTS idx_employees_email ON public.employees(email);
CREATE INDEX IF NOT EXISTS idx_employees_status ON public.employees(status);

-- 컬럼 설명
COMMENT ON TABLE public.employees IS '직원(회원가입 UI와 동일 필드 저장)';
COMMENT ON COLUMN public.employees.name IS '이름';
COMMENT ON COLUMN public.employees.email IS '이메일 (로그인 연동)';
COMMENT ON COLUMN public.employees.phone IS '휴대폰 번호';
COMMENT ON COLUMN public.employees.team IS '소속 팀 (영업팀, 설계팀 등)';
COMMENT ON COLUMN public.employees.showroom IS '소속 전시장 (본점, 제1전시장 등)';
COMMENT ON COLUMN public.employees.birth_date IS '생년월일';
COMMENT ON COLUMN public.employees.position_name IS '직책 (실장, 대리, 팀장 등)';
COMMENT ON COLUMN public.employees.auth_user_id IS 'Supabase Auth 사용자 ID';
COMMENT ON COLUMN public.employees.status IS '승인 상태: pending(대기), approved(승인), blocked(차단)';
COMMENT ON COLUMN public.employees.employee_id IS '사번 (관리자 승인 시 부여, 로그인 ID로 사용)';
