-- ============================================================
-- 관리자 기능: showrooms 테이블 + get_employee_by_auth_id에 permission 반환 추가
-- Supabase SQL Editor에서 실행
-- ============================================================

-- 1. showrooms 테이블 (전시장 관리 CRUD)
CREATE TABLE IF NOT EXISTS public.showrooms (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code text UNIQUE NOT NULL,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.showrooms IS '전시장 목록 (관리자에서 CRUD)';

ALTER TABLE public.showrooms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon all showrooms"
  ON public.showrooms FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_showrooms_code ON public.showrooms(code);

-- 기존 데이터 삽입 (이미 있으면 무시)
INSERT INTO public.showrooms (code, name)
VALUES
  ('headquarters', '본사 전시장'),
  ('showroom1', '1전시장'),
  ('showroom3', '3전시장'),
  ('showroom4', '4전시장'),
  ('ganghwa', '강화전시장')
ON CONFLICT (code) DO NOTHING;

-- 2. get_employee_by_auth_id RPC에 permission 반환 추가 (permission 컬럼이 있는 경우)
-- permission 컬럼이 없으면 아래에서 제거 후 실행
CREATE OR REPLACE FUNCTION public.get_employee_by_auth_id(p_auth_user_id uuid)
RETURNS TABLE(
  id bigint,
  name text,
  team text,
  role text,
  showroom text,
  status text,
  permission text
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT e.id, e.name, e.team, e.role, e.showroom, e.status,
         COALESCE(e.permission, 'staff')::text AS permission
  FROM public.employees e
  WHERE e.auth_user_id = p_auth_user_id
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.get_employee_by_auth_id(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.get_employee_by_auth_id(uuid) TO authenticated;

COMMENT ON FUNCTION public.get_employee_by_auth_id(uuid) IS '로그인: auth_user_id로 직원 조회 (id, name, team, role, showroom, status, permission)';
