-- ============================================================
-- 세움OS: Supabase SQL Editor에서 "Run" 한 번만 실행하세요
-- (employees 테이블 생성 + 로그인/사번용 컬럼 추가)
-- ============================================================

-- 1) employees 테이블이 없으면 생성
CREATE TABLE IF NOT EXISTS public.employees (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  team text,
  role text,
  showroom text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon all employees" ON public.employees;
CREATE POLICY "Allow anon all employees"
  ON public.employees FOR ALL TO anon USING (true) WITH CHECK (true);

-- 2) 로그인/회원가입용 컬럼 추가
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS auth_user_id uuid UNIQUE;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS employee_id text UNIQUE;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS email text;

CREATE INDEX IF NOT EXISTS idx_employees_auth_user_id ON public.employees(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_employees_status ON public.employees(status);
CREATE INDEX IF NOT EXISTS idx_employees_employee_id ON public.employees(employee_id);

-- 인사 정보 (실무형 보강)
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS birth_date date;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS position text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS position_name text;
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS permission text DEFAULT 'staff';
