-- ============================================================
-- 세움OS 핵심 테이블 (기존 테스트 테이블 appointments, costomers, leads 유지)
-- Supabase SQL Editor에서 실행
-- ============================================================

-- 1. reservations (방문예약 고객)
CREATE TABLE IF NOT EXISTS public.reservations (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  phone text,
  visit_date date,
  showroom text,
  manager text,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.reservations IS '방문예약 고객';

-- 2. customers (고객 관리)
CREATE TABLE IF NOT EXISTS public.customers (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  phone text,
  address text,
  source text,
  status text,
  sales_person text,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.customers IS '고객 관리';

-- 3. contracts (계약 목록) - customer_id는 나중에 FK 확장 가능
CREATE TABLE IF NOT EXISTS public.contracts (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_id bigint,
  sales_person text,
  contract_amount numeric,
  deposit numeric,
  middle_payment numeric,
  balance numeric,
  status text,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.contracts IS '계약 목록';

-- 4. payments (입금 관리) - contract_id는 나중에 FK 확장 가능
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contract_id bigint,
  type text,
  amount numeric,
  payment_date date
);

COMMENT ON TABLE public.payments IS '입금 관리';

-- 5. employees (직원 관리)
CREATE TABLE IF NOT EXISTS public.employees (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  team text,
  role text,
  showroom text,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.employees IS '직원 관리';

-- ============================================================
-- Foreign Key (단순 구조, 나중에 확장 시 CASCADE 등 추가 가능)
-- ============================================================

-- contracts.customer_id -> customers.id (선택: 고객 삭제 시 계약은 유지)
ALTER TABLE public.contracts
  ADD CONSTRAINT fk_contracts_customer
  FOREIGN KEY (customer_id) REFERENCES public.customers(id)
  ON DELETE SET NULL;

-- payments.contract_id -> contracts.id (선택: 계약 삭제 시 입금 기록 유지)
ALTER TABLE public.payments
  ADD CONSTRAINT fk_payments_contract
  FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
  ON DELETE SET NULL;

-- ============================================================
-- Row Level Security (RLS) - anon 키로 앱에서 접근 가능하도록
-- 보안 강화 시 나중에 정책 수정
-- ============================================================

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon all reservations"
  ON public.reservations FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Allow anon all customers"
  ON public.customers FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Allow anon all contracts"
  ON public.contracts FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Allow anon all payments"
  ON public.payments FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Allow anon all employees"
  ON public.employees FOR ALL TO anon USING (true) WITH CHECK (true);

-- ============================================================
-- 인덱스 (조회 성능, app.js 필터/정렬에 유리)
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_reservations_visit_date ON public.reservations(visit_date);
CREATE INDEX IF NOT EXISTS idx_reservations_showroom ON public.reservations(showroom);
CREATE INDEX IF NOT EXISTS idx_customers_sales_person ON public.customers(sales_person);
CREATE INDEX IF NOT EXISTS idx_customers_status ON public.customers(status);
CREATE INDEX IF NOT EXISTS idx_contracts_customer_id ON public.contracts(customer_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON public.contracts(status);
CREATE INDEX IF NOT EXISTS idx_payments_contract_id ON public.payments(contract_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON public.payments(payment_date);
CREATE INDEX IF NOT EXISTS idx_employees_team ON public.employees(team);
CREATE INDEX IF NOT EXISTS idx_employees_showroom ON public.employees(showroom);
