-- LG가전 사은품 발주 테이블
-- 주택 계약 시 제공되는 LG가전 사은품 발주·배송 내역 관리
-- 전 팀(영업/설계/시공/정산/마케팅) 공유

CREATE TABLE IF NOT EXISTS public.lg_appliance_orders (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  local_id text UNIQUE,
  showroom_id text,
  contract_local_id text,
  customer_name text,
  sales_person text,
  product text,
  model_name text,
  quantity integer,
  amount numeric,
  order_date date,
  delivery_date date,
  status text DEFAULT '대기',
  delivery_address text,
  phone text,
  memo text,
  payload jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.lg_appliance_orders IS 'LG가전 사은품 발주 — 주택 계약 시 제공';

CREATE INDEX IF NOT EXISTS idx_lg_appliance_orders_local_id ON public.lg_appliance_orders(local_id);
CREATE INDEX IF NOT EXISTS idx_lg_appliance_orders_showroom_id ON public.lg_appliance_orders(showroom_id);
CREATE INDEX IF NOT EXISTS idx_lg_appliance_orders_order_date ON public.lg_appliance_orders(order_date);
CREATE INDEX IF NOT EXISTS idx_lg_appliance_orders_contract_local_id ON public.lg_appliance_orders(contract_local_id);

-- RLS (현 프로젝트는 anon key 로 전 팀 공유하는 패턴이므로 contracts 와 동일하게 공개)
ALTER TABLE public.lg_appliance_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "lg_appliance_orders_all_read" ON public.lg_appliance_orders;
CREATE POLICY "lg_appliance_orders_all_read"
  ON public.lg_appliance_orders FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "lg_appliance_orders_all_write" ON public.lg_appliance_orders;
CREATE POLICY "lg_appliance_orders_all_write"
  ON public.lg_appliance_orders FOR ALL
  USING (true)
  WITH CHECK (true);
