-- 029_contract_drawings.sql
-- 계약 도면(시공/허가/토목/협의/설계) 메타데이터를 별도 테이블로 분리.
-- 기존에는 contracts.payload(JSONB) 안에 도면 URL 문자열을 저장했는데,
-- saveContracts() 가 bulk upsert 라 다른 사용자의 stale localStorage 가
-- payload 를 통째로 덮어쓰면서 도면 URL 이 사라지는 사고가 발생했다.
-- 단일 행 단위 추가/삭제로 stale 충돌을 원천 차단한다.
--
-- 이번 PR 에서는 kind='construction' (시공도면) 만 우선 이전한다.
-- 허가/토목/협의/설계 도면은 후속 PR 에서 같은 패턴으로 이전 예정.

CREATE TABLE IF NOT EXISTS public.contract_drawings (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contract_local_id text NOT NULL,
  kind text NOT NULL CHECK (kind IN ('construction', 'permit', 'civil', 'design', 'discussion')),
  url text NOT NULL,
  path text,
  file_name text,
  uploaded_by text,
  uploaded_at timestamptz DEFAULT now(),
  sort_order integer DEFAULT 0
);

COMMENT ON TABLE public.contract_drawings IS '계약 도면 메타데이터 (시공/허가/토목/협의/설계). stale payload 덮어쓰기 사고 방지를 위해 contracts.payload 에서 분리.';
COMMENT ON COLUMN public.contract_drawings.contract_local_id IS 'contracts.local_id 와 매칭';
COMMENT ON COLUMN public.contract_drawings.kind IS '도면 종류: construction(시공) | permit(허가) | civil(토목) | design(설계) | discussion(협의)';
COMMENT ON COLUMN public.contract_drawings.url IS 'Supabase Storage public URL';
COMMENT ON COLUMN public.contract_drawings.path IS 'Storage 내부 경로 (선택)';
COMMENT ON COLUMN public.contract_drawings.sort_order IS '화면 표시 순서 (오래된 순)';

CREATE INDEX IF NOT EXISTS idx_contract_drawings_contract_kind
  ON public.contract_drawings(contract_local_id, kind);
CREATE INDEX IF NOT EXISTS idx_contract_drawings_uploaded_at
  ON public.contract_drawings(uploaded_at);

-- RLS: contracts 와 동일한 패턴 (anon key 로 전 팀 공유)
ALTER TABLE public.contract_drawings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contract_drawings_all_read" ON public.contract_drawings;
CREATE POLICY "contract_drawings_all_read"
  ON public.contract_drawings FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "contract_drawings_all_write" ON public.contract_drawings;
CREATE POLICY "contract_drawings_all_write"
  ON public.contract_drawings FOR ALL
  USING (true)
  WITH CHECK (true);
