-- 034_site_progress_photos.sql
-- 시공팀 현장파악 - 현장소장이 올리는 현장 진행 사진 메타데이터.
-- 사진 파일은 Supabase Storage(contract_files 버킷)에 저장하고
-- 이 테이블은 url/업로드 시각/업로더 정보만 보관한다.
-- contracts.payload bulk upsert 의 stale 덮어쓰기 사고를 피하기 위해
-- contract_drawings 와 동일한 분리 패턴을 따른다.

CREATE TABLE IF NOT EXISTS public.site_progress_photos (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contract_local_id text NOT NULL,
  url text NOT NULL,
  path text,
  file_name text,
  note text,
  uploaded_by text,
  uploaded_at timestamptz DEFAULT now()
);

COMMENT ON TABLE public.site_progress_photos IS '시공팀 현장파악 - 현장 진행 사진 메타데이터.';
COMMENT ON COLUMN public.site_progress_photos.contract_local_id IS 'contracts.local_id 와 매칭';
COMMENT ON COLUMN public.site_progress_photos.url IS 'Supabase Storage public URL';
COMMENT ON COLUMN public.site_progress_photos.path IS 'Storage 내부 경로';
COMMENT ON COLUMN public.site_progress_photos.note IS '간단 메모(선택)';
COMMENT ON COLUMN public.site_progress_photos.uploaded_by IS '업로더 이름/아이디';

CREATE INDEX IF NOT EXISTS idx_site_progress_photos_contract
  ON public.site_progress_photos(contract_local_id);
CREATE INDEX IF NOT EXISTS idx_site_progress_photos_uploaded_at
  ON public.site_progress_photos(uploaded_at DESC);

ALTER TABLE public.site_progress_photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "site_progress_photos_all_read" ON public.site_progress_photos;
CREATE POLICY "site_progress_photos_all_read"
  ON public.site_progress_photos FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "site_progress_photos_all_write" ON public.site_progress_photos;
CREATE POLICY "site_progress_photos_all_write"
  ON public.site_progress_photos FOR ALL
  USING (true)
  WITH CHECK (true);
