-- 035_haeyoung_submissions.sql
-- 외부 협력 건축사(해영 건축사) 도면 업로드 메타데이터.
-- "부서별 업무 > 설계팀 > 해영 건축사" 메뉴에서 PDF/DWG 도면을
-- 직접 업로드하면 설계팀 + 시공팀 전원에게 인앱/브라우저 알림이 발사된다.
-- 파일 자체는 Supabase Storage 'contract_files' 버킷의
-- 'haeyoung_submissions/...' 경로에 저장.

CREATE TABLE IF NOT EXISTS public.haeyoung_submissions (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  description text,
  file_name text,
  file_url text,
  file_path text,
  file_size bigint,
  file_type text,
  contract_local_id text,
  uploaded_by_name text,
  uploaded_at timestamptz DEFAULT now(),
  is_deleted boolean DEFAULT false
);

COMMENT ON TABLE public.haeyoung_submissions IS '해영 건축사(외부 협력) 도면 업로드 메타데이터.';
COMMENT ON COLUMN public.haeyoung_submissions.contract_local_id IS '연결된 계약 local_id (선택)';
COMMENT ON COLUMN public.haeyoung_submissions.file_url IS 'Supabase Storage public URL';
COMMENT ON COLUMN public.haeyoung_submissions.uploaded_by_name IS '업로드 주체 표시명 (해영 건축사 본인 또는 대리 업로드자)';

CREATE INDEX IF NOT EXISTS idx_haeyoung_submissions_uploaded_at
  ON public.haeyoung_submissions(uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_haeyoung_submissions_contract
  ON public.haeyoung_submissions(contract_local_id);

ALTER TABLE public.haeyoung_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "haeyoung_submissions_all_read" ON public.haeyoung_submissions;
CREATE POLICY "haeyoung_submissions_all_read"
  ON public.haeyoung_submissions FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "haeyoung_submissions_all_write" ON public.haeyoung_submissions;
CREATE POLICY "haeyoung_submissions_all_write"
  ON public.haeyoung_submissions FOR ALL
  USING (true)
  WITH CHECK (true);

-- Realtime 활성화 (업로드 즉시 다른 세션 목록도 갱신)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'haeyoung_submissions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.haeyoung_submissions;
  END IF;
END$$;
